language: go
services:
  - docker
sudo: required
go:
  - "1.10"
addons:
  apt:
    packages:
      - p7zip-full
# - runc

env:
  global:
    - PATH="$HOME/protoc/bin:$PATH"

cache:
# cache timeout in seconds:
  timeout: 1000
  directories:
    - $HOME/pwned-passwords/

before_install:
  - $TRAVIS_BUILD_DIR/.travis/get-protoc.sh
  - go get -u github.com/golang/protobuf/protoc-gen-go
  - $TRAVIS_BUILD_DIR/.travis/get-pwned-passwords.sh

script:
#  - go generate
  - go test -v ./...
  - CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static"' github.com/pedrosland/pwned-check/cmd/pwned-save
  - CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static"' github.com/pedrosland/pwned-check/cmd/pwned-serve
  - "travis_wait sh -c '7za x $HOME/pwned-passwords/pwned-passwords-2.0.txt.7z -so | ./pwned-save -import-file=- -num-passwords=502000000 -save-file=pwned-data.bin'"
#  - docker build .
