// Code generated by protoc-gen-go. DO NOT EDIT.
// source: filter.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type State struct {
	Version              int32         `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Filter               *State_Filter `protobuf:"bytes,2,opt,name=filter" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_filter_89a68dffd88dba05, []int{0}
}
func (m *State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State.Unmarshal(m, b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State.Marshal(b, m, deterministic)
}
func (dst *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(dst, src)
}
func (m *State) XXX_Size() int {
	return xxx_messageInfo_State.Size(m)
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *State) GetFilter() *State_Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

type State_Filter struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Lookups              int32    `protobuf:"varint,2,opt,name=lookups" json:"lookups,omitempty"`
	Count                int64    `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *State_Filter) Reset()         { *m = State_Filter{} }
func (m *State_Filter) String() string { return proto.CompactTextString(m) }
func (*State_Filter) ProtoMessage()    {}
func (*State_Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_filter_89a68dffd88dba05, []int{0, 0}
}
func (m *State_Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State_Filter.Unmarshal(m, b)
}
func (m *State_Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State_Filter.Marshal(b, m, deterministic)
}
func (dst *State_Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State_Filter.Merge(dst, src)
}
func (m *State_Filter) XXX_Size() int {
	return xxx_messageInfo_State_Filter.Size(m)
}
func (m *State_Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_State_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_State_Filter proto.InternalMessageInfo

func (m *State_Filter) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *State_Filter) GetLookups() int32 {
	if m != nil {
		return m.Lookups
	}
	return 0
}

func (m *State_Filter) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*State)(nil), "proto.State")
	proto.RegisterType((*State_Filter)(nil), "proto.State.Filter")
}

func init() { proto.RegisterFile("filter.proto", fileDescriptor_filter_89a68dffd88dba05) }

var fileDescriptor_filter_89a68dffd88dba05 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xcb, 0xcc, 0x29,
	0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x73, 0x18, 0xb9,
	0x58, 0x83, 0x4b, 0x12, 0x4b, 0x52, 0x85, 0x24, 0xb8, 0xd8, 0xcb, 0x52, 0x8b, 0x8a, 0x33, 0xf3,
	0xf3, 0x24, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0x60, 0x5c, 0x21, 0x6d, 0x2e, 0x36, 0x88, 0x56,
	0x09, 0x26, 0x05, 0x46, 0x0d, 0x6e, 0x23, 0x61, 0x88, 0x11, 0x7a, 0x60, 0x7d, 0x7a, 0x6e, 0x60,
	0xa9, 0x20, 0xa8, 0x12, 0x29, 0x1f, 0x2e, 0x36, 0x88, 0x88, 0x90, 0x10, 0x17, 0x4b, 0x4a, 0x62,
	0x49, 0x22, 0xd8, 0x34, 0x9e, 0x20, 0x30, 0x1b, 0x64, 0x49, 0x4e, 0x7e, 0x7e, 0x76, 0x69, 0x41,
	0x31, 0xd8, 0x2c, 0xd6, 0x20, 0x18, 0x57, 0x48, 0x84, 0x8b, 0x35, 0x39, 0xbf, 0x34, 0xaf, 0x44,
	0x82, 0x59, 0x81, 0x51, 0x83, 0x39, 0x08, 0xc2, 0x49, 0x62, 0x03, 0xdb, 0x64, 0x0c, 0x08, 0x00,
	0x00, 0xff, 0xff, 0xc5, 0xad, 0x96, 0xf0, 0xbc, 0x00, 0x00, 0x00,
}
